"""empty message

Revision ID: f9cea04422ef
Revises: 
Create Date: 2021-08-02 19:23:25.993901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cea04422ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'user_id')
    # ### end Alembic commands ###
